apiVersion: v1beta3
kind: Service
metadata:
  labels:
    name: monitoring-grafana
    kubernetes.io/cluster-service: "true"
  name: monitoring-grafana
spec:
  targetPort: 80
  port: 80
  selector:
    name: influxGrafana
