apiVersion: v1beta3
kind: ReplicationController
metadata:
  labels:
    name: influxGrafana
  name: monitoring-influx-grafana-controller
spec:
  replicas: 1
  selector:
    name: influxGrafana
  template:
    metadata:
      labels:
        name: influxGrafana
    spec:
      containers:
        - image: kubernetes/heapster_influxdb:v0.3
          name: influxdb
          ports:
            - containerPort: 8083
            - containerPort: 8086
        - name: grafana
          image: kubernetes/heapster_grafana:v0.5
          ports:
              - containerPort: 80
          env:
            - name: "HTTP_USER"
              value: "admin"
            - name: "HTTP_PASS"
              value: "**None**"
            - name: "INFLUXDB_PROTO"
              value: '"+window.location.protocol.slice(0,-1)+"'
            - name: "INFLUXDB_HOST"
              value: '"+window.location.host+"'
            - name: "INFLUXDB_PORT"
              value: ""
            - name: "KUBERNETES_API_PORT"
              value: ""
