apiVersion: v1beta3
kind: Service
metadata:
  labels:
    name: monitoring-influxdb
    kubernetes.io/cluster-service: "true"
  name: monitoring-influxdb
spec:
  ports:
    - port: 80
      targetPort: 8086
  selector:
    name: influxGrafana
