apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: kafkaSink
  name: kafkaSink
  namespace: kube-system
spec:
  replicas: 1
  selector:
    name: kafka
  template:
    metadata:
      labels:
        name: kafka
    spec:
      containers:
      - name: kafka
        image: kubernetes/heapster_kafka:canary
        env:
          - name: ADVERTISED_PORT
            value: 9092
